import type { Config } from 'tailwindcss'

const config = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './config/**/*.{js,ts,jsx,tsx,mdx}',
    './entities/**/*.{js,ts,jsx,tsx,mdx}',
    './features/**/*.{js,ts,jsx,tsx,mdx}',
    './hooks/**/*.{js,ts,jsx,tsx,mdx}',
    './i18n/**/*.{js,ts,jsx,tsx,mdx}',
    './lib/**/*.{js,ts,jsx,tsx,mdx}',
    './messages/**/*.{js,ts,jsx,tsx,mdx}',
    './shared/**/*.{js,ts,jsx,tsx,mdx}',
    './styles/**/*.{js,ts,jsx,tsx,mdx}',
    './types/**/*.{js,ts,jsx,tsx,mdx}',
    './utils/**/*.{js,ts,jsx,tsx,mdx}',
    './widgets/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: 'var(--background)',
        foreground: 'var(--foreground)',
        card: {
          DEFAULT: 'var(--card)',
          foreground: 'var(--card-foreground)',
        },
        popover: {
          DEFAULT: 'var(--popover)',
          foreground: 'var(--popover-foreground)',
        },
        primary: {
          DEFAULT: 'var(--primary)',
          foreground: 'var(--primary-foreground)',
        },
        secondary: {
          DEFAULT: 'var(--secondary)',
          foreground: 'var(--secondary-foreground)',
        },
        muted: {
          DEFAULT: 'var(--muted)',
          foreground: 'var(--muted-foreground)',
        },
        accent: {
          DEFAULT: 'var(--accent)',
          foreground: 'var(--accent-foreground)',
        },
        destructive: {
          DEFAULT: 'var(--destructive)',
          foreground: 'var(--destructive-foreground)',
        },
        border: 'var(--border)',
        input: 'var(--input)',
        ring: 'var(--ring)',
        brand: {
          DEFAULT: 'var(--brand)',
          foreground: 'var(--brand-foreground)',
          accent: 'var(--brand-accent)',
        },
        surface: {
          DEFAULT: 'var(--surface)',
          elevated: 'var(--surface-elevated)',
          subtle: 'var(--surface-subtle)',
          inverse: 'var(--surface-inverse)',
          glass: 'var(--surface-glass)',
          'glass-strong': 'var(--surface-glass-strong)',
        },
        chart: {
          1: 'var(--chart-1)',
          2: 'var(--chart-2)',
          3: 'var(--chart-3)',
          4: 'var(--chart-4)',
          5: 'var(--chart-5)',
        },
        sidebar: {
          DEFAULT: 'var(--sidebar)',
          foreground: 'var(--sidebar-foreground)',
          primary: 'var(--sidebar-primary)',
          'primary-foreground': 'var(--sidebar-primary-foreground)',
          accent: 'var(--sidebar-accent)',
          'accent-foreground': 'var(--sidebar-accent-foreground)',
          border: 'var(--sidebar-border)',
          ring: 'var(--sidebar-ring)',
        },
        kizuna: {
          primary: 'var(--kizuna-primary)',
          canvas: 'var(--kizuna-canvas)',
          surface: 'var(--kizuna-surface)',
          'text-main': 'var(--kizuna-text-main)',
          'text-muted': 'var(--kizuna-text-muted)',
          border: 'var(--kizuna-border)',
        },
      },
      fontFamily: {
        sans: ['var(--font-body)'],
        serif: ['var(--font-heading)'],
        mono: ['var(--font-code)'],
      },
      fontSize: {
        'heading-2xl': ['5.5rem', { lineHeight: '0.95', fontWeight: '500' }],
        'heading-xl': ['4rem', { lineHeight: '1', fontWeight: '500' }],
        'heading-lg': ['3rem', { lineHeight: '1.05', fontWeight: '500' }],
        'heading-md': ['2.25rem', { lineHeight: '1.1', fontWeight: '600' }],
        'heading-sm': ['1.5rem', { lineHeight: '1.2', fontWeight: '600' }],
        'body-lg': ['1.125rem', { lineHeight: '1.75rem' }],
        'body-md': ['1rem', { lineHeight: '1.625rem' }],
        'body-sm': ['0.875rem', { lineHeight: '1.375rem' }],
        caption: ['0.75rem', { lineHeight: '1rem' }],
        eyebrow: ['0.6875rem', { lineHeight: '1rem', letterSpacing: '0.2em', fontWeight: '700' }],
      },
      borderRadius: {
        xs: 'var(--radius-token-xs)',
        sm: 'var(--radius-token-sm)',
        md: 'var(--radius-token-md)',
        lg: 'var(--radius-token-lg)',
        xl: 'var(--radius-token-xl)',
        '2xl': 'var(--radius-token-2xl)',
        '3xl': 'var(--radius-token-3xl)',
        '4xl': 'var(--radius-token-4xl)',
      },
      boxShadow: {
        card: 'var(--shadow-token-card)',
        dropdown: 'var(--shadow-token-dropdown)',
        glass: 'var(--shadow-token-glass)',
        glow: 'var(--shadow-token-glow)',
        'glow-strong': 'var(--shadow-token-glow-strong)',
        ambient: 'var(--shadow-token-ambient)',
      },
      spacing: {
        page: 'var(--spacing-page)',
        'page-lg': 'var(--spacing-page-lg)',
        section: 'var(--spacing-section)',
        'section-lg': 'var(--spacing-section-lg)',
      },
      zIndex: {
        hide: 'var(--z-hide)',
        base: 'var(--z-base)',
        raised: 'var(--z-raised)',
        header: 'var(--z-header)',
        dropdown: 'var(--z-dropdown)',
        overlay: 'var(--z-overlay)',
        modal: 'var(--z-modal)',
        popover: 'var(--z-popover)',
        toast: 'var(--z-toast)',
        tooltip: 'var(--z-tooltip)',
      },
    },
  },
} satisfies Config

export default config
